# Generated by Django 3.0.3 on 2020-04-20 22:13

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_column='matricula', max_length=7, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_0-9]*$', 'Ingrese matricula en mayusculas y sin espacio')])),
                ('marca', models.CharField(db_column='marca', max_length=20)),
                ('modelo', models.CharField(db_column='modelo', max_length=20)),
                ('viajes', models.IntegerField(db_column='viajes_asignados', default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)])),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('No disponible', 'No disponible')], db_column='estado', default='Disponible', max_length=13)),
            ],
            options={
                'verbose_name': 'Camion',
                'verbose_name_plural': 'Camiones',
                'db_table': 'Camion',
                'ordering': ['matricula', 'estado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Chacra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=50, unique=True)),
                ('ubicacion', models.TextField(db_column='Ubicacion', max_length=100)),
                ('observacion', models.CharField(blank=True, db_column='Observacion', max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', default='Activo', max_length=10)),
            ],
            options={
                'verbose_name': 'Chacra',
                'verbose_name_plural': 'Chacras',
                'db_table': 'Chacra',
                'ordering': ['nombre', 'estado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(db_column='nombre', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]+(?: [A-Z0-9]+)*$', 'Solo se admiten mayúsculas')])),
                ('direccion', models.TextField(db_column='direccion', max_length=100)),
                ('celular', models.CharField(db_column='celular', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese solo números sin el cero inicial')])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'db_table': 'Planta',
                'ordering': ['nombre', 'estado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=15)),
                ('zafra', models.CharField(db_column='Zafra', max_length=4, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese año de zafra')])),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['zafra', 'nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celular', models.CharField(db_column='celular', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese solo números sin el cero inicial')])),
                ('direccion', models.TextField(db_column='direccion', max_length=100)),
                ('razonsocial', models.TextField(db_column='razonSocial', max_length=80)),
                ('rut', models.CharField(db_column='rut', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese formato correcto para RUT, solo 12 números')])),
                ('nombre', models.CharField(db_column='nombre', max_length=15)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('email', models.CharField(blank=True, db_column='email', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', default='Activo', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Productor',
                'verbose_name_plural': 'Productores',
                'db_table': 'Productor',
                'ordering': ['user', 'estado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('rut', models.CharField(db_column='RUT', max_length=12, unique=True, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese formato correcto para RUT, solo 12 números')])),
                ('direccion', models.TextField(db_column='Direccion', max_length=100)),
                ('celular', models.CharField(db_column='celular', max_length=8, validators=[django.core.validators.RegexValidator('^[0-9_]*$', 'Ingrese solo números sin el cero inicial')])),
                ('email', models.CharField(blank=True, db_column='eMail', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], db_column='estado', default='Activo', max_length=20)),
            ],
            options={
                'verbose_name': 'Transportista',
                'verbose_name_plural': 'Transportistas',
                'db_table': 'Transportista',
                'ordering': ['nombre', 'estado'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('observaciones', models.TextField(blank=True, db_column='observaciones', max_length=80)),
                ('fecha_hora_creacion', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('Rechazado', 'Rechazado'), ('Entregado', 'Entregado')], db_column='estado', default='Pendiente', max_length=20)),
                ('chacra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Chacra')),
                ('idcamion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gestor.Camion')),
                ('idplanta', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='gestor.Planta')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='gestor.Producto')),
                ('productor', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='gestor.Productor')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'reserva',
                'ordering': ['-fecha_hora', 'productor'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chacra',
            name='productor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Productor'),
        ),
        migrations.AddField(
            model_name='camion',
            name='idtransportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Transportista'),
        ),
    ]
