# Generated by Django 3.0.3 on 2020-04-24 03:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_auto_20200420_2353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True, 'ordering': ['-fecha', 'productor'], 'verbose_name': 'reserva', 'verbose_name_plural': 'reservas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha',
            field=models.DateField(default=datetime.date(2020, 4, 24)),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.time(3, 0, 38, 213121)),
        ),
    ]
