# Generated by Django 3.0.3 on 2020-04-28 15:33

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_auto_20200428_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_creacion',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.time(15, 33, 24, 45490)),
        ),
    ]
