# Generated by Django 3.0.3 on 2020-05-20 02:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_auto_20200429_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='observacion_rechazo',
            field=models.TextField(blank=True, db_column='observacion por rechazo', max_length=80),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
